name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t your-dockerhub-username/hello-world .
        docker push your-dockerhub-username/hello-world