apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: hello-world-kafka
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal